on: pull_request

env:
  PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
  PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}

jobs:
  lint-code:
    runs-on: ubuntu-latest
    name: Perform Checks
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Notify on failure
        uses: kha7iq/pingme-action@v1
        if: failure()
        env:
          PUSHOVER_TITLE: '🟢 New Request: ${{ github.ref }}'
          PUSHOVER_MESSAGE: 'Event is triggerd by ${{ github.event_name }} Checks  ❌  ${{ job.status }}'
        with:
          service: pushover

      - name: Notify on success
        uses: kha7iq/pingme-action@v1
        if: success()
        env:
          PUSHOVER_TITLE: '🟢 New Request: ${{ github.ref }}'
          PUSHOVER_MESSAGE: 'Event is triggerd by ${{ github.event_name }} Checks ✅  ${{ job.status }}'
        with:
          service: pushover
